# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IxN6vHZerbP_8J6BmERZdC9hHt7t95A
"""

pip install -q kora

from kora.selenium import wd

import pandas as pd
from google.colab.data_table import DataTable
from time import sleep

def busca_carteira_teorica(indice, espera=8):
  url = f'https://sistemaswebb3-listados.b3.com.br/indexPage/day/{indice.upper()}?language=pt-br'
  wd.get(url)
  sleep(espera)

  wd.find_element_by_id('segment').send_keys('Setor de Atuação')
  sleep(espera)

  wd.find_element_by_link_text('Download').click()
  sleep(espera)

  arquivos = !ls -1t *.csv
  return pd.read_csv(arquivos[0], sep=';', encoding= ' ISO-8859-1',skipfooter=2, engine='python', thousands='.', decimal='.', header =1, index_col=False)

ibov = busca_carteira_teorica('ibov')

ibov

ifix = busca_carteira_teorica('ifix', 3)

DataTable(ifix)

